parameters:
 
zombies:
  immuneToDaylight: true
  hordeSize: 10
  spawnChance: 50
  spawnInterval: 60
  blockBreakSpawnInterval: 15
  maximumHealth: 50
  spawnMinimumDistance: 5
  spawnMaximumDistance: 10